apiVersion: v1
kind: Service
metadata:
  name: kodilla-quotes
  labels:
    app: kodilla-quotes
spec:
  type: NodePort
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 32221
  selector:
    app: kodilla-quotes